#ifndef ZRSPECTRUMPLUGIN_GLOBAL_H
#define ZRSPECTRUMPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ZRSPECTRUMPLUGIN_LIBRARY)
#define ZRSPECTRUMPLUGIN_EXPORT Q_DECL_EXPORT
#else
#define ZRSPECTRUMPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // ZRSPECTRUMPLUGIN_GLOBAL_H
